# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Teste do projeto

on:
  push:
    branches: [ "main", "release/**" ]
    tags:        
    - v*
    paths-ignore:
    - '**.md'
    - '**.sh'
    - '**.json'
  pull_request:
    branches: [ "main", "release/**" ]
    tags:        
    - v*
    paths-ignore:
    - '**.md'
    - '**.sh'
    - '**.json'

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
    - name: Verificando checkstyle
      run: mvn checkstyle:check -Dmaven.test.skip=true

  pmd:
    needs: ["checkstyle"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
    - name: Verificando PMD
      run: mvn pmd:check -Dmaven.test.skip=true

  spotbugs:
    needs: ["pmd"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
    - name: Verificando spotbugs
      run: mvn spotbugs:check -Dmaven.test.skip=true

  test:
    needs: ["spotbugs"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven

    - name: Teste do projeto
      run: mvn -B test -pl api-say-hello

  build:
    needs: ["test"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven

    - name: Build do projeto
      run: mvn -B package -Dmaven.test.skip=true

# ---------------------------------------